using System.Text;
using System.Text.Json;

namespace NTFSReport;

public static class HtmlGenerator
{
    private static readonly JsonSerializerOptions JsonOpts = new() { WriteIndented = false };

    // -----------------------------------------------------------------------
    // Single-path report
    // -----------------------------------------------------------------------
    public static string BuildReport(ScanResult result)
    {
        var json   = SerializeFolders(result.AllFolders);
        var date   = result.ScanDate.ToString("yyyy-MM-dd HH:mm");
        var path   = EscapeHtml(result.Options.RootPath);
        var brokenWarning = result.BrokenInheritanceCount > 0
            ? $"""<div class="stat warning-stat"><div class="stat-label">&#9888; Broken Inheritance</div><div class="stat-value">{result.BrokenInheritanceCount}</div></div>"""
            : "";

        return $"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>NTFS Permissions &mdash; {path}</title>
            {GetStyles()}
            </head>
            <body>
            <div class="header">
              <div class="header-brand">ProDirt</div>
              <h1>NTFS Permissions Report</h1>
              <div class="stats">
                <div class="stat"><div class="stat-label">Root Path</div><div class="stat-value path-stat">{path}</div></div>
                <div class="stat"><div class="stat-label">Folders</div><div class="stat-value">{result.TotalFolders}</div></div>
                <div class="stat"><div class="stat-label">Permissions</div><div class="stat-value">{result.TotalPermissions}</div></div>
                <div class="stat"><div class="stat-label">Errors</div><div class="stat-value">{result.TotalErrors}</div></div>
                {brokenWarning}
                <div class="stat"><div class="stat-label">Generated</div><div class="stat-value path-stat">{date}</div></div>
                <div class="stat"><div class="stat-label">Scan Time</div><div class="stat-value path-stat">{result.Elapsed.TotalSeconds:F1}s</div></div>
              </div>
            </div>
            <div class="controls">
              <div class="search-row">
                <input type="text" id="searchBox" placeholder="Search folders, paths, or identities...">
                <button onclick="expandAll()">Expand All</button>
                <button onclick="collapseAll()">Collapse All</button>
                <button onclick="expandToLevel(1)">Level 1</button>
                <button onclick="expandToLevel(2)">Level 2</button>
                <button onclick="expandToLevel(3)">Level 3</button>
                <button class="btn-warning" onclick="showBrokenOnly()" title="Show only folders with broken inheritance">&#9888; Broken Inheritance Only</button>
                <button class="btn-secondary" onclick="exportCsv()">Export CSV</button>
              </div>
              {(result.BrokenInheritanceCount > 0 ? GetBrokenInheritanceLegend() : "")}
            </div>
            <div class="container">
              <div id="loading" class="loading">Building tree structure...</div>
              <div class="tree-container" id="treeContainer" style="display:none"></div>
            </div>
            <div class="footer">
              <span>Generated by <strong>ProDirt NTFS Permissions Reporter</strong> &nbsp;|&nbsp; <a href="https://prodirt-llc.github.io" target="_blank">prodirt-llc.github.io</a></span>
            </div>
            {GetSingleScript(json, result.Options.RootPath)}
            </body>
            </html>
            """;
    }

    // -----------------------------------------------------------------------
    // Side-by-side comparison report
    // -----------------------------------------------------------------------
    public static string BuildComparisonReport(ComparisonResult comparison)
    {
        var leftJson  = SerializeFolders(comparison.Left.AllFolders);
        var rightJson = SerializeFolders(comparison.Right.AllFolders);
        var date      = DateTime.Now.ToString("yyyy-MM-dd HH:mm");
        var leftPath  = EscapeHtml(comparison.Left.Options.RootPath);
        var rightPath = EscapeHtml(comparison.Right.Options.RootPath);

        return $"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>NTFS Comparison Report</title>
            {GetStyles()}
            {GetComparisonStyles()}
            </head>
            <body>
            <div class="header">
              <div class="header-brand">ProDirt</div>
              <h1>NTFS Permissions Comparison</h1>
              <div class="stats">
                <div class="stat"><div class="stat-label">Generated</div><div class="stat-value path-stat">{date}</div></div>
                <div class="stat"><div class="stat-label">Same Folders</div><div class="stat-value">{comparison.SameCount}</div></div>
                <div class="stat diff-changed"><div class="stat-label">Changed</div><div class="stat-value">{comparison.ChangedCount}</div></div>
                <div class="stat diff-left"><div class="stat-label">Left Only</div><div class="stat-value">{comparison.LeftOnlyCount}</div></div>
                <div class="stat diff-right"><div class="stat-label">Right Only</div><div class="stat-value">{comparison.RightOnlyCount}</div></div>
              </div>
            </div>
            <div class="controls">
              <div class="search-row">
                <input type="text" id="searchBox" placeholder="Search folders or identities...">
                <button onclick="expandAll()">Expand All</button>
                <button onclick="collapseAll()">Collapse All</button>
                <button onclick="showChangedOnly()">Show Changes Only</button>
              </div>
              <div class="compare-legend">
                <span class="leg leg-changed">Changed permissions</span>
                <span class="leg leg-left">Left path only</span>
                <span class="leg leg-right">Right path only</span>
                <span class="leg leg-same">Identical</span>
                <span class="leg leg-broken">&#9888; Broken Inheritance</span>
              </div>
            </div>
            <div class="compare-header-row">
              <div class="compare-path-label left-label">PATH A: {leftPath}</div>
              <div class="compare-path-label right-label">PATH B: {rightPath}</div>
            </div>
            <div class="compare-body">
              <div id="leftLoading" class="loading">Building left tree...</div>
              <div id="rightLoading" class="loading">Building right tree...</div>
              <div class="tree-container" id="leftTree" style="display:none"></div>
              <div class="tree-container" id="rightTree" style="display:none"></div>
            </div>
            <div class="footer">
              <span>Generated by <strong>ProDirt NTFS Permissions Reporter</strong> &nbsp;|&nbsp; <a href="https://prodirt-llc.github.io" target="_blank">prodirt-llc.github.io</a></span>
            </div>
            {GetComparisonScript(leftJson, rightJson, comparison.Left.Options.RootPath, comparison.Right.Options.RootPath)}
            </body>
            </html>
            """;
    }

    // -----------------------------------------------------------------------
    // Private helpers
    // -----------------------------------------------------------------------
    private static string SerializeFolders(List<FolderNode> folders)
    {
        var sb = new StringBuilder("[");
        for (int i = 0; i < folders.Count; i++)
        {
            var f = folders[i];
            if (i > 0) sb.Append(',');
            sb.Append("{\"p\":").Append(JsonStr(f.Path));
            sb.Append(",\"n\":").Append(JsonStr(f.Name));
            sb.Append(",\"pr\":").Append(JsonStr(f.ParentPath));
            sb.Append(",\"d\":").Append(f.Depth);
            if (f.InheritanceBroken) sb.Append(",\"bi\":true");
            if (f.AccessDenied)      sb.Append(",\"ad\":true");

            // Only serialize EXPLICIT (non-inherited) permissions.
            // Inherited perms are resolved at display time by walking up folderMap in the JS.
            var explicit_ = f.Permissions.Where(p => !p.IsInherited).ToList();
            var inherited_ = f.Permissions.Where(p => p.IsInherited).ToList();
            sb.Append(",\"pm\":[");
            for (int j = 0; j < explicit_.Count; j++)
            {
                var p = explicit_[j];
                if (j > 0) sb.Append(',');
                sb.Append("{\"i\":").Append(JsonStr(p.Identity));
                var rights = (!string.IsNullOrEmpty(p.RightsDecoded) && p.RightsDecoded != p.Rights)
                    ? p.RightsDecoded : p.Rights;
                sb.Append(",\"r\":").Append(JsonStr(rights));
                if (p.AccessType != "Allow") sb.Append(",\"a\":").Append(JsonStr(p.AccessType));
                sb.Append('}');
            }
            // Store inherited count so JS knows how many exist
            int inheritedCount = inherited_.Count;
            sb.Append("]");
            if (inheritedCount > 0) sb.Append(",\"ic\":").Append(inheritedCount);
            sb.Append('}');
        }
        sb.Append(']');
        return sb.ToString();
    }

    private static string JsonStr(string s) => JsonSerializer.Serialize(s, JsonOpts);

    private static string EscapeHtml(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    private static string GetBrokenInheritanceLegend() => """
        <div class="bi-notice">
          <strong>&#9888; Warning:</strong> Folders highlighted in amber have NTFS inheritance <strong>disabled</strong>.
          Permissions on these folders are set explicitly and are not inherited from the parent.
          This may indicate intentional security boundaries or misconfigured ACLs &mdash; review carefully.
        </div>
        """;

    private static string GetStyles() => """
        <style>
        *{margin:0;padding:0;box-sizing:border-box}
        body{font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background:#f5f5f5;color:#2c3e50}
        .header{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:28px 24px;box-shadow:0 4px 12px rgba(0,0,0,0.15)}
        .header-brand{font-size:11px;font-weight:700;letter-spacing:3px;text-transform:uppercase;opacity:.75;margin-bottom:6px}
        h1{font-size:26px;font-weight:600;margin-bottom:12px}
        .stats{display:flex;gap:16px;flex-wrap:wrap;margin-top:12px}
        .stat{background:rgba(255,255,255,0.18);padding:10px 16px;border-radius:8px;backdrop-filter:blur(4px)}
        .stat-label{font-size:11px;opacity:.85;margin-bottom:3px;text-transform:uppercase;letter-spacing:.5px}
        .stat-value{font-size:20px;font-weight:700}
        .path-stat{font-size:13px;font-family:monospace;word-break:break-all}
        .warning-stat{background:rgba(255,193,7,0.3);border:1px solid rgba(255,193,7,0.5)}
        .diff-changed{background:rgba(255,152,0,.3);border:1px solid rgba(255,152,0,.5)}
        .diff-left{background:rgba(33,150,243,.3);border:1px solid rgba(33,150,243,.5)}
        .diff-right{background:rgba(156,39,176,.3);border:1px solid rgba(156,39,176,.5)}
        .controls{background:white;padding:16px 24px;border-bottom:1px solid #e0e0e0;box-shadow:0 2px 4px rgba(0,0,0,0.06)}
        .search-row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}
        input[type=text]{flex:1;min-width:280px;padding:10px 14px;border:2px solid #e0e0e0;border-radius:6px;font-size:14px;transition:border-color .2s}
        input[type=text]:focus{outline:none;border-color:#667eea}
        button{padding:8px 16px;background:#667eea;color:white;border:none;border-radius:6px;cursor:pointer;font-size:13px;font-weight:600;transition:all .15s;white-space:nowrap}
        button:hover{background:#5568d3;transform:translateY(-1px)}
        .btn-warning{background:#f39c12}.btn-warning:hover{background:#e08e0b}
        .btn-secondary{background:#6c757d}.btn-secondary:hover{background:#5a6268}
        .bi-notice{margin-top:12px;background:#fff8e6;border:1px solid #f39c12;border-radius:6px;padding:10px 14px;font-size:13px;color:#856404}
        .container{padding:20px 24px;max-width:2000px;margin:0 auto}
        .tree-container{background:white;border-radius:8px;padding:20px;box-shadow:0 2px 8px rgba(0,0,0,0.08)}
        .folder-node{margin:1px 0}
        .folder-header{display:flex;align-items:center;padding:7px 10px;cursor:pointer;border-radius:4px;transition:background .12s;position:relative}
        .folder-header:hover{background:#f0f4ff}
        .expand-icon{width:20px;height:20px;display:inline-flex;align-items:center;justify-content:center;margin-right:5px;font-size:12px;font-weight:bold;color:#667eea;user-select:none;flex-shrink:0;font-family:monospace}
        .expand-icon.has-children.collapsed::before{content:'[+]'}
        .expand-icon.has-children.expanded::before{content:'[-]'}
        .expand-icon.no-children{visibility:hidden}
        .folder-icon{margin-right:6px;font-size:15px;flex-shrink:0}
        .folder-name{flex:1;font-weight:500;font-size:13.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
        .perm-count{background:#e8ecff;color:#667eea;padding:2px 9px;border-radius:10px;font-size:11px;font-weight:700;margin-left:6px;flex-shrink:0}
        .perm-count.has-deny{background:#fde;color:#c0392b}
        .perm-button{background:#667eea;color:white;padding:3px 10px;border-radius:4px;font-size:11px;border:none;cursor:pointer;margin-left:6px;flex-shrink:0;font-weight:600}
        .perm-button:hover{background:#5568d3}
        .bi-badge{color:#b8860b;font-size:12px;margin-left:6px;flex-shrink:0;white-space:nowrap;opacity:0.8}
        .ad-badge{background:#e74c3c;color:white;padding:2px 9px;border-radius:10px;font-size:10px;margin-left:6px;flex-shrink:0;white-space:nowrap}
        .folder-header.broken-inheritance{background:#fff8e6;border-left:3px solid #f39c12}
        .folder-header.broken-inheritance:hover{background:#fff0cc}
        .folder-header.access-denied{background:#fdf0f0;border-left:3px solid #e74c3c}
        .children-container{margin-left:24px;display:none}
        .children-container.expanded{display:block}
        .permissions-panel{margin:4px 0 8px 46px;background:#f8f9fc;border-left:3px solid #667eea;border-radius:0 4px 4px 0;display:none;overflow-x:auto}
        .permissions-panel.visible{display:block}
        table{width:100%;border-collapse:collapse;font-size:12px}
        th{background:#e9ecef;padding:7px 10px;text-align:left;font-weight:700;font-size:11px;color:#495057;white-space:nowrap;position:sticky;top:0}
        td{padding:7px 10px;border-bottom:1px solid #e9ecef;vertical-align:top}
        tr:last-child td{border-bottom:none}
        tr:hover td{background:#f0f4ff}
        .rights-decoded{color:#2c3e50;font-weight:600;display:block}
        .rights-raw{color:#adb5bd;font-size:10px;font-family:monospace;display:block}
        .allow{color:#27ae60;font-weight:700}
        .deny{color:#e74c3c;font-weight:700}
        .inherited-yes{color:#adb5bd;font-size:11px}
        .inherited-no{color:#e67e22;font-size:11px;font-weight:600}
        .loading{text-align:center;padding:48px;color:#6c757d;font-size:16px}
        .footer{text-align:center;padding:16px;color:#adb5bd;font-size:12px;margin-top:8px}
        .footer a{color:#667eea;text-decoration:none}
        .footer a:hover{text-decoration:underline}
        </style>
        """;

    private static string GetComparisonStyles() => """
        <style>
        .compare-header-row{display:flex;gap:0;background:white;border-bottom:1px solid #dee2e6}
        .compare-path-label{flex:1;padding:10px 20px;font-size:12px;font-family:monospace;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
        .left-label{background:#e3f2fd;color:#1565c0;border-right:2px solid #dee2e6}
        .right-label{background:#f3e5f5;color:#6a1b9a}
        .compare-body{display:flex;gap:12px;min-height:400px;padding:20px 24px}
        .compare-body .tree-container{flex:1;min-width:0}
        .compare-legend{display:flex;gap:12px;flex-wrap:wrap;margin-top:10px;align-items:center}
        .leg{padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600}
        .leg-changed{background:#fff3e0;color:#e65100;border:1px solid #ffcc02}
        .leg-left{background:#e3f2fd;color:#1565c0;border:1px solid #90caf9}
        .leg-right{background:#f3e5f5;color:#6a1b9a;border:1px solid #ce93d8}
        .leg-same{background:#e8f5e9;color:#1b5e20;border:1px solid #a5d6a7}
        .leg-broken{background:#fff8e6;color:#856404;border:1px solid #f39c12}
        .folder-header.diff-changed{background:#fff8e0;border-left:3px solid #ff9800}
        .folder-header.diff-left{background:#e8f4fd;border-left:3px solid #2196f3}
        .folder-header.diff-right{background:#f8f0fc;border-left:3px solid #9c27b0}
        .diff-changed-badge{background:#ff9800;color:white;padding:2px 8px;border-radius:10px;font-size:10px;font-weight:700;margin-left:6px;flex-shrink:0}
        .diff-only-badge{background:#9e9e9e;color:white;padding:2px 8px;border-radius:10px;font-size:10px;margin-left:6px;flex-shrink:0}
        </style>
        """;

    private static string GetSingleScript(string json, string rootPath) => $$"""
        <script>
        const flatData = {{json}};
        const rootPath = {{JsonSerializer.Serialize(rootPath)}};
        console.log('Loaded ' + flatData.length + ' folders');
        const folderMap = new Map();
        flatData.forEach(f => { f.children = []; folderMap.set(f.p, f); });
        flatData.forEach(f => { if (f.pr && folderMap.has(f.pr)) folderMap.get(f.pr).children.push(f); });
        const rootFolder = flatData.find(f => !f.pr || f.pr === f.p) || flatData[0];

        function hasDenyRule(pm) { return pm && pm.some(p => p.a === 'Deny'); }

        function createNode(folder, parentEl) {
          const nodeDiv = document.createElement('div');
          nodeDiv.className = 'folder-node';
          nodeDiv.dataset.path = folder.p;
          nodeDiv.dataset.depth = folder.d;
          if (folder.bi) nodeDiv.dataset.bi = '1';
          if (folder.ad) nodeDiv.dataset.ad = '1';

          const hasKids = folder.children && folder.children.length > 0;
          const hasDeny = hasDenyRule(folder.pm);

          const header = document.createElement('div');
          let headerClass = 'folder-header';
          if (folder.bi) headerClass += ' broken-inheritance';
          else if (folder.ad) headerClass += ' access-denied';
          header.className = headerClass;

          const icon = document.createElement('span');
          icon.className = hasKids ? 'expand-icon has-children collapsed' : 'expand-icon no-children';

          const folderIcon = document.createElement('span');
          folderIcon.className = 'folder-icon';
          folderIcon.textContent = folder.ad ? '\uD83D\uDD12' : (folder.bi ? '\u26A0\uFE0F' : '\uD83D\uDCC1');

          const name = document.createElement('span');
          name.className = 'folder-name';
          name.textContent = folder.n || folder.p;
          name.title = folder.p;

          const count = document.createElement('span');
          count.className = 'perm-count' + (hasDeny ? ' has-deny' : '');
          // Show explicit count + inherited count from ancestors
          const ownExplicit = folder.pm ? folder.pm.length : 0;
          let ancInherited = 0;
          let ancCur = folder;
          while (ancCur && ancCur.pr) {
            const anc = folderMap.get(ancCur.pr);
            if (!anc) break;
            ancInherited += anc.pm ? anc.pm.length : 0;
            ancCur = anc;
          }
          count.textContent = ownExplicit + ancInherited;
          if (ownExplicit === 0 && ancInherited > 0) count.title = ancInherited + ' inherited';
          else if (ancInherited > 0) count.title = ownExplicit + ' explicit + ' + ancInherited + ' inherited';

          const btn = document.createElement('button');
          btn.className = 'perm-button';
          btn.textContent = 'Perms';
          btn.onclick = e => { e.stopPropagation(); togglePerms(nodeDiv); };

          header.appendChild(icon);
          header.appendChild(folderIcon);
          header.appendChild(name);
          header.appendChild(count);
          header.appendChild(btn);

          if (folder.bi) {
            const badge = document.createElement('span');
            badge.className = 'bi-badge';
            badge.textContent = '\u26A0';
            badge.title = 'Inheritance disabled — permissions are set explicitly on this folder, not inherited from parent.';
            header.appendChild(badge);
          }
          if (folder.ad) {
            const badge = document.createElement('span');
            badge.className = 'ad-badge';
            badge.textContent = '\uD83D\uDD12 Access Denied';
            header.appendChild(badge);
          }

          if (hasKids) header.onclick = () => toggleKids(nodeDiv, icon);

          const panel = document.createElement('div');
          panel.className = 'permissions-panel';
          {
            const explicitPerms = folder.pm || [];
            // Walk up folderMap collecting all ancestor explicit perms
            const inheritedRows = [];
            let cur = folder;
            while (cur && cur.pr) {
              const anc = folderMap.get(cur.pr);
              if (!anc) break;
              if (anc.pm && anc.pm.length > 0) {
                anc.pm.forEach(p => inheritedRows.push({ p, src: anc.p }));
              }
              cur = anc;
            }
            let html = '<table><thead><tr><th>Identity</th><th>Rights</th><th>Access</th><th>Source</th></tr></thead><tbody>';
            if (explicitPerms.length > 0) {
              html += '<tr><td colspan="4" style="background:#f0f4ff;font-size:11px;font-weight:700;color:#667eea;padding:4px 10px;letter-spacing:.5px">EXPLICIT PERMISSIONS</td></tr>';
              explicitPerms.forEach(p => {
                const ac = (p.a && p.a !== 'Allow') ? 'deny' : 'allow';
                html += '<tr><td>' + escHtml(p.i) + '</td><td><span class="rights-decoded">' + escHtml(p.r) + '</span></td><td class="' + ac + '">' + (p.a||'Allow') + '</td><td><span class="inherited-no">Explicit</span></td></tr>';
              });
            }
            if (inheritedRows.length > 0) {
              html += '<tr><td colspan="4" style="background:#f8f9fc;font-size:11px;font-weight:700;color:#6c757d;padding:4px 10px;letter-spacing:.5px">INHERITED PERMISSIONS</td></tr>';
              inheritedRows.forEach(({ p, src }) => {
                const ac = (p.a && p.a !== 'Allow') ? 'deny' : 'allow';
                const shortSrc = src.split('\\').pop() || src;
                html += '<tr style="opacity:0.85"><td>' + escHtml(p.i) + '</td><td><span class="rights-decoded">' + escHtml(p.r) + '</span></td><td class="' + ac + '">' + (p.a||'Allow') + '</td><td><span class="inherited-yes" title="' + escHtml(src) + '">&#8593; ' + escHtml(shortSrc) + '</span></td></tr>';
              });
            }
            if (explicitPerms.length === 0 && inheritedRows.length === 0) {
              html += '<tr><td colspan="4" style="padding:10px;color:#6c757d">No permissions found' + (folder.ad ? ' (Access Denied)' : '') + '</td></tr>';
            }
            html += '</tbody></table>';
            panel.innerHTML = html;
          }

          nodeDiv.appendChild(header);
          nodeDiv.appendChild(panel);

          if (hasKids) {
            const cont = document.createElement('div');
            cont.className = 'children-container';
            folder.children.forEach(kid => createNode(kid, cont));
            nodeDiv.appendChild(cont);
          }
          parentEl.appendChild(nodeDiv);
        }

        function escHtml(s) {
          if (!s) return '';
          return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
        }
        // Walk up the folder map to find the nearest ancestor with explicit permissions
        function findPermSource(folder) {
          let cur = folder;
          while (cur && cur.pr) {
            const parent = folderMap.get(cur.pr);
            if (!parent) break;
            if (parent.pm && parent.pm.length > 0) return parent;
            cur = parent;
          }
          return null;
        }
        function toggleKids(node, icon) {
          const cont = node.querySelector(':scope > .children-container');
          if (!cont) return;
          const exp = cont.classList.toggle('expanded');
          icon.classList.toggle('collapsed', !exp);
          icon.classList.toggle('expanded', exp);
        }
        function togglePerms(node) { node.querySelector('.permissions-panel').classList.toggle('visible'); }
        function expandAll() {
          document.querySelectorAll('.children-container').forEach(e => e.classList.add('expanded'));
          document.querySelectorAll('.expand-icon.has-children').forEach(e => { e.classList.remove('collapsed'); e.classList.add('expanded'); });
        }
        function collapseAll() {
          document.querySelectorAll('.children-container').forEach(e => e.classList.remove('expanded'));
          document.querySelectorAll('.expand-icon.has-children').forEach(e => { e.classList.add('collapsed'); e.classList.remove('expanded'); });
          document.querySelectorAll('.permissions-panel').forEach(e => e.classList.remove('visible'));
        }
        function expandToLevel(lvl) {
          collapseAll();
          document.querySelectorAll('.folder-node').forEach(n => {
            const d = parseInt(n.dataset.depth);
            if (d < lvl) {
              const cont = n.querySelector(':scope > .children-container');
              const ic = n.querySelector(':scope > .folder-header > .expand-icon.has-children');
              if (cont && ic) { cont.classList.add('expanded'); ic.classList.remove('collapsed'); ic.classList.add('expanded'); }
            }
          });
        }
        function showBrokenOnly() {
          collapseAll();
          let found = false;
          document.querySelectorAll('.folder-node').forEach(n => {
            if (n.dataset.bi) {
              n.style.display = 'block';
              // Make ancestors visible too
              let p = n.parentElement;
              while (p) {
                if (p.classList.contains('folder-node')) p.style.display = 'block';
                if (p.classList.contains('children-container')) p.classList.add('expanded');
                p = p.parentElement;
              }
              n.querySelector(':scope > .folder-header > .expand-icon')?.classList.remove('collapsed');
              found = true;
            }
          });
          // Hide non-broken nodes that weren't revealed as ancestors
          document.querySelectorAll('.folder-node').forEach(n => {
            if (!n.dataset.bi && n.style.display !== 'block') n.style.display = 'none';
          });
          if (!found) alert('No broken inheritance folders found in this scan.');
        }
        document.getElementById('searchBox').addEventListener('input', e => {
          const term = e.target.value.toLowerCase().trim();
          if (!term) {
            document.querySelectorAll('.folder-node').forEach(n => n.style.display = '');
            return;
          }
          document.querySelectorAll('.folder-node').forEach(n => {
            const show = n.dataset.path.toLowerCase().includes(term)
              || n.querySelector('.folder-name')?.textContent.toLowerCase().includes(term)
              || Array.from(n.querySelectorAll('td')).some(td => td.textContent.toLowerCase().includes(term));
            n.style.display = show ? 'block' : 'none';
          });
        });

        function exportCsv() {
          const rows = [['Path','Depth','BrokenInheritance','Identity','AccessType','Rights','IsInherited','Flags']];
          flatData.forEach(f => {
            if (!f.pm || f.pm.length === 0) {
              rows.push([f.p, f.d, f.bi ? 'TRUE':'FALSE', '', '', '', '', '']);
            } else {
              f.pm.forEach(p => rows.push([f.p, f.d, f.bi?'TRUE':'FALSE', p.i, p.a, p.d||p.r, p.h, p.f]));
            }
          });
          const csv = rows.map(r => r.map(c => '"' + String(c||'').replace(/"/g,'""') + '"').join(',')).join('\r\n');
          const blob = new Blob(['\uFEFF'+csv], {type:'text/csv;charset=utf-8'});
          const a = document.createElement('a');
          a.href = URL.createObjectURL(blob);
          a.download = 'ntfs_permissions.csv';
          a.click();
        }

        document.getElementById('loading').textContent = 'Rendering tree (' + flatData.length + ' folders)...';
        setTimeout(() => {
          if (rootFolder) createNode(rootFolder, document.getElementById('treeContainer'));
          document.getElementById('loading').style.display = 'none';
          document.getElementById('treeContainer').style.display = 'block';
        }, 50);
        </script>
        """;

    private static string GetComparisonScript(string leftJson, string rightJson, string leftRoot, string rightRoot) => $$"""
        <script>
        const leftData  = {{leftJson}};
        const rightData = {{rightJson}};
        const leftRoot  = {{JsonSerializer.Serialize(leftRoot)}};
        const rightRoot = {{JsonSerializer.Serialize(rightRoot)}};

        function getRelPath(fullPath, root) {
          if (fullPath === root) return '';
          return fullPath.slice(root.length).replace(/^[\/\\]+/, '').toLowerCase();
        }

        const leftByRel  = new Map();
        const rightByRel = new Map();
        leftData.forEach(f  => { f.rel = getRelPath(f.p, leftRoot);  leftByRel.set(f.rel,  f); });
        rightData.forEach(f => { f.rel = getRelPath(f.p, rightRoot); rightByRel.set(f.rel, f); });

        function permsKey(pm) { return (pm||[]).map(p => p.i+'|'+p.a+'|'+p.r).sort().join(';'); }

        leftData.forEach(f => {
          const r = rightByRel.get(f.rel);
          if (!r) f.diffStatus = 'left-only';
          else if (permsKey(f.pm) === permsKey(r.pm)) f.diffStatus = 'same';
          else f.diffStatus = 'changed';
        });
        rightData.forEach(f => {
          const l = leftByRel.get(f.rel);
          if (!l) f.diffStatus = 'right-only';
          else if (permsKey(f.pm) === permsKey(l.pm)) f.diffStatus = 'same';
          else f.diffStatus = 'changed';
        });

        function buildTree(data) {
          data.forEach(f => { f.children = []; });
          const map = new Map(data.map(f => [f.p, f]));
          data.forEach(f => { if (f.pr && map.has(f.pr)) map.get(f.pr).children.push(f); });
          return data.find(f => !f.pr || f.pr === f.p) || data[0];
        }

        const leftRoot2  = buildTree(leftData);
        const rightRoot2 = buildTree(rightData);

        function escHtml(s) {
          if (!s) return '';
          return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
        }

        function createCompareNode(folder, parentEl) {
          const nodeDiv = document.createElement('div');
          nodeDiv.className = 'folder-node';
          nodeDiv.dataset.path = folder.p;
          nodeDiv.dataset.rel  = folder.rel;
          nodeDiv.dataset.depth = folder.d;
          nodeDiv.dataset.diff = folder.diffStatus;

          const hasKids = folder.children && folder.children.length > 0;
          const header = document.createElement('div');

          let hClass = 'folder-header';
          if (folder.bi) hClass += ' broken-inheritance';
          if (folder.diffStatus === 'changed')    hClass += ' diff-changed';
          if (folder.diffStatus === 'left-only')  hClass += ' diff-left';
          if (folder.diffStatus === 'right-only') hClass += ' diff-right';
          header.className = hClass;

          const icon = document.createElement('span');
          icon.className = hasKids ? 'expand-icon has-children collapsed' : 'expand-icon no-children';

          const fi = document.createElement('span');
          fi.className = 'folder-icon';
          fi.textContent = folder.ad ? '\uD83D\uDD12' : (folder.bi ? '\u26A0\uFE0F' : '\uD83D\uDCC1');

          const name = document.createElement('span');
          name.className = 'folder-name';
          name.textContent = folder.n || folder.p;
          name.title = folder.p;

          const cnt = document.createElement('span');
          cnt.className = 'perm-count';
          cnt.textContent = (folder.pm||[]).length;

          const btn = document.createElement('button');
          btn.className = 'perm-button';
          btn.textContent = 'Perms';
          btn.onclick = e => { e.stopPropagation(); togglePerms(nodeDiv); };

          header.appendChild(icon); header.appendChild(fi); header.appendChild(name);
          header.appendChild(cnt); header.appendChild(btn);

          if (folder.bi) {
            const b = document.createElement('span'); b.className = 'bi-badge';
            b.textContent = '\u26A0 Broken'; header.appendChild(b);
          }
          if (folder.diffStatus === 'changed') {
            const b = document.createElement('span'); b.className = 'diff-changed-badge';
            b.textContent = '\u2260 Changed'; header.appendChild(b);
          } else if (folder.diffStatus === 'left-only' || folder.diffStatus === 'right-only') {
            const b = document.createElement('span'); b.className = 'diff-only-badge';
            b.textContent = folder.diffStatus === 'left-only' ? '\u2190 Left Only' : 'Right Only \u2192';
            header.appendChild(b);
          }

          if (hasKids) header.onclick = () => toggleKids(nodeDiv, icon);

          const panel = document.createElement('div');
          panel.className = 'permissions-panel';
          if (folder.pm && folder.pm.length > 0) {
            let html = '<table><thead><tr><th>Identity</th><th>Rights</th><th>Access</th><th>Inherited</th></tr></thead><tbody>';
            folder.pm.forEach(p => {
              const ac = p.a === 'Allow' ? 'allow' : 'deny';
              const inh = p.h ? '<span class="inherited-yes">Yes</span>' : '<span class="inherited-no">No</span>';
              html += '<tr><td>' + escHtml(p.i) + '</td><td><span class="rights-decoded">' + escHtml(p.d||p.r) + '</span></td><td class="' + ac + '">' + p.a + '</td><td>' + inh + '</td></tr>';
            });
            html += '</tbody></table>';
            panel.innerHTML = html;
          }

          nodeDiv.appendChild(header);
          nodeDiv.appendChild(panel);

          if (hasKids) {
            const cont = document.createElement('div');
            cont.className = 'children-container';
            folder.children.forEach(kid => createCompareNode(kid, cont));
            nodeDiv.appendChild(cont);
          }
          parentEl.appendChild(nodeDiv);
        }

        function toggleKids(node, icon) {
          const cont = node.querySelector(':scope > .children-container');
          if (!cont) return;
          const exp = cont.classList.toggle('expanded');
          icon.classList.toggle('collapsed', !exp);
          icon.classList.toggle('expanded', exp);
        }
        function togglePerms(node) { node.querySelector('.permissions-panel').classList.toggle('visible'); }
        function expandAll() {
          document.querySelectorAll('.children-container').forEach(e => e.classList.add('expanded'));
          document.querySelectorAll('.expand-icon.has-children').forEach(e => { e.classList.remove('collapsed'); e.classList.add('expanded'); });
        }
        function collapseAll() {
          document.querySelectorAll('.children-container').forEach(e => e.classList.remove('expanded'));
          document.querySelectorAll('.expand-icon.has-children').forEach(e => { e.classList.add('collapsed'); e.classList.remove('expanded'); });
          document.querySelectorAll('.permissions-panel').forEach(e => e.classList.remove('visible'));
        }
        function showChangedOnly() {
          document.querySelectorAll('.folder-node').forEach(n => {
            const d = n.dataset.diff;
            n.style.display = (d === 'changed' || d === 'left-only' || d === 'right-only') ? 'block' : 'none';
          });
        }
        document.getElementById('searchBox').addEventListener('input', e => {
          const term = e.target.value.toLowerCase().trim();
          document.querySelectorAll('.folder-node').forEach(n => {
            n.style.display = (!term || n.dataset.path.toLowerCase().includes(term) || (n.dataset.rel||'').toLowerCase().includes(term)) ? '' : 'none';
          });
        });

        document.getElementById('leftLoading').textContent  = 'Rendering left tree ('  + leftData.length  + ' folders)...';
        document.getElementById('rightLoading').textContent = 'Rendering right tree (' + rightData.length + ' folders)...';
        setTimeout(() => {
          if (leftRoot2)  createCompareNode(leftRoot2,  document.getElementById('leftTree'));
          if (rightRoot2) createCompareNode(rightRoot2, document.getElementById('rightTree'));
          document.getElementById('leftLoading').style.display  = 'none';
          document.getElementById('rightLoading').style.display = 'none';
          document.getElementById('leftTree').style.display  = 'block';
          document.getElementById('rightTree').style.display = 'block';
        }, 50);
        </script>
        """;
}
