"""
Generates the NTFS Folder Audit app icon: app.ico, icon.png and icon.svg.

    python make_icon.py          (requires: pip install pillow)

The magnifier IS the icon rather than a badge on a folder. At taskbar size a
folder plus a magnifier are two shapes competing for about 250 pixels and
neither survives; one dominant silhouette, with its handle breaking the
circle, stays recognisable all the way down to 16px.

Everything is drawn at 8x and downsampled per target size, so each size gets
real antialiasing instead of being a squashed copy of the 256px master. Sizes
at or below 24px thicken the key and drop one tooth - at that scale the
original proportions close up into a blob.
"""
import os
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
SS   = 8

# Amber ring reads against both a light Explorer list and a dark taskbar.
# The app's near-black slate would match the UI chrome but disappears on dark.
STEEL_BACK = (43, 74, 106, 255)
AMBER      = (217, 119, 6, 255)
WHITE      = (255, 255, 255, 255)

ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]

# Geometry as fractions of the canvas, shared by the raster and SVG output.
CX, CY, R  = .44, .42, .31     # lens centre and inner radius
RING       = .085              # ring thickness
HX, HY, HW = .87, .87, .15     # handle end point and width


def draw(size, small):
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    S = size
    cx, cy, rr, lw = S*CX, S*CY, S*R, S*RING

    # Handle first, so the ring paints over the joint.
    d.line([(cx + rr*.78, cy + rr*.78), (S*HX, S*HY)],
           fill=AMBER, width=max(int(S*HW), 2))
    d.ellipse([cx-rr-lw, cy-rr-lw, cx+rr+lw, cy+rr+lw], fill=AMBER)
    d.ellipse([cx-rr, cy-rr, cx+rr, cy+rr], fill=WHITE)

    # Key, sized off the lens interior so it scales with the ring.
    u  = rr / 100.0
    bx, br = cx - u*34, u*36
    hr = u*15 if small else u*14
    sh = u*20 if small else u*17
    d.ellipse([bx-br, cy-br, bx+br, cy+br], fill=STEEL_BACK)
    d.ellipse([bx-hr, cy-hr, bx+hr, cy+hr], fill=WHITE)
    d.rounded_rectangle([bx+br*.55, cy-sh/2, cx+u*76, cy+sh/2],
                        radius=max(1, int(u*6)), fill=STEEL_BACK)
    tw = u*17 if small else u*14
    for t in ([u*40] if small else [u*30, u*58]):
        d.rounded_rectangle([bx+br*.55+t, cy+sh/2, bx+br*.55+t+tw, cy+sh/2+u*34],
                            radius=max(1, int(u*5)), fill=STEEL_BACK)
    return img


def render(size):
    return draw(size * SS, small=size <= 24).resize((size, size), Image.LANCZOS)


def svg(S=256):
    hexof = lambda c: "#%02x%02x%02x" % c[:3]
    cx, cy, rr, lw = S*CX, S*CY, S*R, S*RING
    u  = rr / 100.0
    bx, br, hr, sh = cx - u*34, u*36, u*14, u*17
    sx = bx + br*.55
    teeth = "".join(
        f'\n  <rect x="{sx+t:.2f}" y="{cy+sh/2:.2f}" width="{u*14:.2f}" '
        f'height="{u*34:.2f}" rx="{u*5:.2f}" fill="{hexof(STEEL_BACK)}"/>'
        for t in (u*30, u*58))
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {S} {S}" width="{S}" height="{S}">
  <!-- NTFS Folder Audit - generated by make_icon.py, do not hand-edit -->
  <line x1="{cx+rr*.78:.2f}" y1="{cy+rr*.78:.2f}" x2="{S*HX:.2f}" y2="{S*HY:.2f}"
        stroke="{hexof(AMBER)}" stroke-width="{S*HW:.2f}" stroke-linecap="round"/>
  <circle cx="{cx:.2f}" cy="{cy:.2f}" r="{rr+lw:.2f}" fill="{hexof(AMBER)}"/>
  <circle cx="{cx:.2f}" cy="{cy:.2f}" r="{rr:.2f}" fill="{hexof(WHITE)}"/>
  <circle cx="{bx:.2f}" cy="{cy:.2f}" r="{br:.2f}" fill="{hexof(STEEL_BACK)}"/>
  <circle cx="{bx:.2f}" cy="{cy:.2f}" r="{hr:.2f}" fill="{hexof(WHITE)}"/>
  <rect x="{sx:.2f}" y="{cy-sh/2:.2f}" width="{cx+u*76-sx:.2f}" height="{sh:.2f}"
        rx="{u*6:.2f}" fill="{hexof(STEEL_BACK)}"/>{teeth}
</svg>
"""


if __name__ == "__main__":
    frames = [render(s) for s in ICO_SIZES]
    ico = os.path.join(HERE, "app.ico")
    frames[-1].save(ico, format="ICO", sizes=[(s, s) for s in ICO_SIZES])
    frames[-1].save(os.path.join(HERE, "icon.png"))
    with open(os.path.join(HERE, "icon.svg"), "w", encoding="utf-8") as fh:
        fh.write(svg())
    print(f"app.ico  {os.path.getsize(ico):,} bytes  sizes={ICO_SIZES}")
    print("icon.png, icon.svg written")
